/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "createHuman-test.check" instead.
 */

#include <check.h>

#line 1 "createHuman-test.check"
#include "personExample.h"

// checkmk createHuman-test.check >createHuman-test.c
// make -f make-test.mk chtest

struct Person
{
    char name[20];
    char subject[20];
    char grade;
    int id;
    short int age;
};

START_TEST(pstruct)
{
#line 16
for (int j = 0; j < sizeof(int); j++)
{
  for (int i =0; i < sizeof(short int); i++)
  {
    struct Person me = createHuman("S","A",'A',j+1,i+1);
    fail_if(strcmp(me.name, "S"), "Wrong Name pstruct");
    fail_unless(strcmp(me.name, "Yari"), "Right Name pstruct");
  }
}
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, pstruct);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
