/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "personExample-test.check" instead.
 */

#include <check.h>

#line 1 "personExample-test.check"
#include "personExample.h"

struct Person
{
    char name[20];
    char subject[20];
    char grade;
    int id;
    short int age;
};

//#test pstruct
//for (int j = 0; j < sizeof(int); j++)
//{
//  for (int i =0; i < sizeof(short int); i++)
//  {
//    struct Person me = createHuman("S","A",'A',j+1,i+1);
//    fail_if(strcmp(me.name, "S"), "Wrong name Name pstruct");
//    fail_unless(strcmp(me.name, "Yari"), "Right Name pstruct");
//  }
//}
START_TEST(personstruct)
{
#line 23
    struct Person me = createPerson();
    fail_if(!strcmp(me.name, "Steve"), "Right Name");
    fail_unless(!strcmp(me.name, "Yari"), "Right Name");

}
END_TEST

START_TEST(createPerson1)
{
#line 28
    struct Person he_man = createPerson();
    fail_unless(!strcmp(he_man.name, "Yari"), "Not the same name");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, personstruct);
    tcase_add_test(tc1_1, createPerson1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
